### ISSUE TITLE
Suggestion to use `deleteById(id)`

### ISSUE THREAD

**Issue by driversti** [dashakrolik/surf-forecast-backend#13]
https://github.com/dashakrolik/surf-forecast-backend/blob/0b46b33ff238589a958c0a0eea8954450bb063a1/src/main/java/com/ordina/surfforecast/service/BeachService.java#L126

You could use `deleteById(id)` here and get rid of this redundant piece of code

**Comment by dashakrolik** [comment]
Thanks, will do

**Comment by driversti** [comment]
If you're really interested in the development of the app I can help you with that. What do you think?

**Comment by dashakrolik** [comment]
Thank you for offering @driversti ! I would be happy to, but I am working on this with my colleagues from Ordina :) But if you would like to fork it and play around with it, feel free! Only thing is I need to change the ApiKey to an env var first I think 😄

**Comment by driversti** [comment]
If you could explain to me what exactly your backend service has to do it would be much easier to help you with that
